# https://travis-ci.org/WillSkywalker/blog
language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"
  - "pypy3"

install: 
  - pip install -r requirements.txt

script: 
  - python manage.py test --coverage